# Generated by Django 3.1.2 on 2020-10-16 09:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Описание события')),
                ('activate_registration', models.BooleanField(default=False, verbose_name='Включить регистрацию')),
                ('activate_notification', models.BooleanField(default=False, verbose_name='Включить оповещение')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('en_notification_time_range', models.BooleanField(default=False)),
                ('start_time_range', models.TimeField(default=datetime.time(0, 0))),
                ('end_time_range', models.TimeField(default=datetime.time(0, 0))),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.event', verbose_name='Событие')),
            ],
        ),
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_service', models.CharField(choices=[('SMS_1', 'SMS service 1 (test)')], max_length=20, verbose_name='Сервис рассылки СМС')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raise_dt', models.DateTimeField(auto_now_add=True, verbose_name='Начало события')),
                ('fall_dt', models.DateTimeField(auto_now_add=True, verbose_name='Завершение события')),
                ('processing', models.BooleanField(default=False, verbose_name='В обработке')),
                ('done', models.BooleanField(default=False, verbose_name='Обработано')),
                ('sended', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('received', models.BooleanField(default=False, verbose_name='Доставлено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='notifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.notifier'),
        ),
    ]
