# Generated by Django 3.1.2 on 2020-10-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owencloud_connector', '0004_auto_20201022_1236'),
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cloud_event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owencloud_connector.cloudevent', verbose_name='Id события OwenCloud'),
        ),
        migrations.AlterField(
            model_name='event',
            name='activate_registration',
            field=models.BooleanField(default=True, verbose_name='Включить регистрацию'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='fall_dt',
            field=models.DateTimeField(blank=True, verbose_name='Завершение события'),
        ),
    ]
