# Generated by Django 3.1.2 on 2020-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_auto_20201023_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='notifier',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='notifier',
            name='sms_service_token',
            field=models.CharField(default='a', max_length=200, verbose_name='Токен подключения к СМС сервису'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifier',
            name='sms_service',
            field=models.CharField(choices=[('SMS.RU', 'SMS.RU')], max_length=20, verbose_name='Сервис рассылки СМС'),
        ),
    ]
