# Generated by Django 3.1.2 on 2020-10-16 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('RU', 'RU'), ('UA', 'UA')], default='RU', max_length=2)),
                ('token', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CloudEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200, verbose_name='Id события в OwenCloud')),
                ('вумшсу_id', models.CharField(max_length=200, verbose_name='Id устройства')),
                ('event_description', models.CharField(max_length=200, verbose_name='Описание события')),
                ('cloud_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owencloud_connector.cloudconnector', verbose_name='Id коннектора')),
            ],
        ),
    ]
