# Generated by Django 3.1.2 on 2020-10-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owencloud_connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudconnector',
            options={'verbose_name': 'Коннектор OwenCloud', 'verbose_name_plural': 'Коннекторы OwenCloud'},
        ),
        migrations.RenameField(
            model_name='cloudevent',
            old_name='вумшсу_id',
            new_name='device_id',
        ),
    ]
