# Generated by Django 3.1.2 on 2020-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owencloud_connector', '0002_auto_20201016_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudevent',
            options={'verbose_name': 'Событие OwenCloud', 'verbose_name_plural': 'События OwenCloud'},
        ),
        migrations.AlterField(
            model_name='cloudconnector',
            name='domain',
            field=models.CharField(choices=[('UA', 'UA'), ('RU', 'RU')], default='RU', max_length=2),
        ),
    ]
